### ISSUE TITLE
Add a way to load plugin on runtime

### ISSUE THREAD

**Issue by maicol07** [ycs77/inertia-plugin#1]
**Is your feature request related to a problem? Please describe.**
I want my users to be able to install plugins with composer and be able to use them without building JS with Vite.

**Describe the solution you'd like**
An alternative way to load plugins on runtime

**Comment by ycs77** [comment]
Release [v0.4.0](https://github.com/ycs77/inertia-plugin/releases/tag/v0.4.0), more details in [docs](https://github.com/ycs77/inertia-plugin/blob/c556212fe5ec120b22ecde3d7fc437a0beea8f84/README.md#build-for-runtime).
