### ISSUE TITLE
Support for Vue3 Composition API

### ISSUE THREAD

**Issue by craigrileyuk** [ycs77/inertia-plugin#4]
At the moment, this plugin works perfectly for the Options API in Vue 2 and 3.

However, I'm having problems when it comes to using it with Vue 3's Composition API since rather than using `this` to access the host app's state, you import functions that return that state (e.g. `usePage`, `getCurrentInstance` and `inject`).

All of the above functions return `null` when using the Composition API since the imports in your addons don't resolve to the same place as the same imports your host app.

Environment: runtime registration
Builder: Vite

**Comment by ycs77** [comment]
Hi @craigrileyuk, thanks for your report, but after my test, the vue 3 composition API component is very dependent on the bundler, recommended using the [Build for Static](https://github.com/ycs77/inertia-page-loader?tab=readme-ov-file#build-for-static) instead.
