### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by anditsung** [ycs77/inertia-plugin#5]
**Use Version:**
Use version when bugs appear.
- vite: v4 / laravel-mix v6.0.0
- inertia-plugin: v0.6.0

after adding this on app.js
```
import { resolvePage } from "~inertia";
```

resolvedNamespaces is not iterable
<img width="1102" alt="Screenshot 2023-05-23 at 15 33 13" src="https://github.com/ycs77/inertia-plugin/assets/1090413/f5dc47ab-5973-4522-8f3b-3a49e4c67553">

i try to create a package using nova4 tool

main app using vite4
nova tool package using mix6

**Comment by ycs77** [comment]
Hi @anditsung, I currently do not use Nova and did not plan to support it.
