### ISSUE TITLE
Can the inertia-plugin be used by a laravel app to render a vue file from a locally hosted laravel package?

### ISSUE THREAD

**Issue by connecteev** [ycs77/inertia-plugin#7]
This is more of a question about how this plugin can be used. Here's a clean repo running Laravel, that isolates a problem I am having:
https://github.com/connecteev/laravel_dummy_code_for_package_customization

This Laravel app makes use of a package that is running Inertia + Vue.js, and uses Vite for asset bundling.  Link: https://github.com/connecteev/laravel_dummy_code_for_package_customization/tree/main/_LOCAL_PACKAGES/keenbrain_dummy_package/

All the context you would need to get this running and understand the problem is in the README.md 

This is the error I am getting from the package when I run the application and go to http://127.0.0.1:8000/foo:

```
GET http://[::1]:5173/resources/js/Pages/Foo.vue net::ERR_ABORTED 404 (Not Found)
index.js:4 Uncaught (in promise) Error: Page not found: ./Pages/Foo.vue
    at resolvePageComponent (index.js:4:15)
    at resolve (app.js:13:24)
    at r (createInertiaApp.ts:34:54)
    at j2 (createInertiaApp.ts:38:24)
    at app.js:11:1
```

I see the same problem when I go to a different route: http://127.0.0.1:8000/portal
In both cases, the Page (Vue file) cannot be rendered, even though it exists in the package: https://github.com/connecteev/laravel_dummy_code_for_package_customization/tree/main/_LOCAL_PACKAGES/keenbrain_dummy_package/resources/js/Pages

Can this Inertia-Plugin be used to fix this problem? If so, can you point me to how that can be done?

**Comment by ycs77** [comment]
Hi, I think you need to install and import the `inertia-plugin` (now renamed to `inertia-page-loader`):

```bash
npm i inertia-page-loader -D
```

Import in `vite.config.js`:

```js
...
import InertiaPageLoader from 'inertia-page-loader/vite'

export default defineConfig({
    plugins: [
        laravel({
            ...
        }),
        vue({
            ...
        }),
        InertiaPageLoader({
            namespaces: [
                // register the Inertia vue pages path
                { keenbrain_dummy_package: '_LOCAL_PACKAGES/keenbrain_dummy_package/resources/js/pages' },
            ],
        }),
    ],
})
```

Wrap the `resolvePage()` function in `resources/js/app.js`:

```diff
+import { resolvePage } from '~inertia'

 createInertiaApp({
-    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
+    // don't change to oneline arrow function
+    resolve: resolvePage(() => {
+      return import.meta.glob('./Pages/**/*.vue')
+    }),
 });
```

Change back the `@vite` blade tag in `resources/views/app.blade.php` and `_LOCAL_PACKAGES/keenbrain_dummy_package/resources/views/app.blade.php`:

```diff
 <!DOCTYPE html>
 <html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
     <head>
         <!-- Scripts -->
+        @routes
-        @vite(['resources/js/app.js', "resources/js/Pages/{$page['component']}.vue"])
+        @vite('resources/js/app.js')
         @inertiaHead
     </head>
 </html>
```

Now you can be using the views in the package with `Inertia::render()`:

```php
Route::get('/foo', function () {
    return Inertia::render('keenbrain_dummy_package::Foo');
})->name('foo');

class MyPortalController
{
    public function __invoke(Request $request, $type = null, $id = null)
    {
        return Inertia::render('keenbrain_dummy_package::MyPortal');
    }
}
```

For more information please see [the package README](https://github.com/ycs77/inertia-page-loader?tab=readme-ov-file).
